### ISSUE TITLE
phonegap build support

### ISSUE THREAD

**Issue by Medioman92** [Wikitude/wikitude-cordova-plugin#100]
hi,
is phonegap build support a planned feature ?
alternately is there any plan to support cordova npm plugin format ?

i'm building through a build server and can't manually add your plugin

**Comment by AndreasSchacherbauerWikitude** [comment]
PhoneGap Build was not a option for use because of some license issues. Sorry :(

**Comment by Medioman92** [comment]
so your website should replace everywhere "phonegap" with "cordova". :+1: 
Phonegap is basically a cloud building system which is based on cordova APIs, if the plugin is not supporting this system it's pretty misleading for someone who reads your documentation

**Comment by bukosabino** [comment]
Any version of Wikitude Plugin is supported with Adobe Phonegap Build?

**Comment by pnagele** [comment]
Hi. Have a look at this npm module, which replicates this plugin for use with Phonegap Build:

https://www.npmjs.com/package/com.wikitude.phonegap.wikitudeplugin

**Comment by bukosabino** [comment]
Hi @pnagele , I've tried with:
npm i com.wikitude.phonegap.wikitudeplugin --save
But, Wikitude is not working :(

If I build manually everything is OK!

**Comment by pnagele** [comment]
Can you describe the error message you see? What exactly is failing?

**Comment by xims** [comment]
Hello,
I'm trying to make simple example working in my app's environment but can't make it work.

I'm using Phonegap Build for cloud builds for iOS and Android.

Into my html file I've added :
 <script src="https://www.wikitude.com/libs/architect.js"></script>
 <script type="text/javascript" src="libs/ade.js"></script>

(created libs/ade.js from https://github.com/Wikitude/wikitude-sdk-samples/blob/master/ade.js)

Into config.xml I've added :
    <plugin name="com.wikitude.phonegap.WikitudePlugin" spec="https://github.com/Wikitude/wikitude-cordova-plugin" />
    <platform name="android">
        <preference name="android-minSdkVersion" value="15" />
    </platform>

I've created source based on 
https://github.com/Wikitude/wikitude-sdk-samples/blob/master/01_ImageRecognition_1_ImageOnTarget/js/imageontarget.js

I couldn't find a way to enter trial licence because the plugin being loaded by Phonegap Cloud Build...

I'm getting errors 
AR is not defined...

What am I doing wrong?

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @xims,
`AR is not defined` usually means that our JS API is not loaded at the time the Architect World is loaded. Architect Worlds are usually the files that include the Wikitude JS API as shown in our examples. You then use our Cordova plugin to load such Architect Worlds.

The license key needs to be changed in the WikitudePlugin.js (This file might be included multiple times in your project, so make sure that you change it in all files).

**Comment by xims** [comment]
Hi @AndreasSchacherbauerWikitude 
Thanks for the reply.

How do I use the Cordova plugin to load Architect Worlds, What's the command for it?
Sorry, I couldn't find anything in the https://github.com/Wikitude/wikitude-sdk-samples/tree/master/01_ImageRecognition_1_ImageOnTarget example.

Also, how can I provide licence number if I use PhoneGap Build to build in the cloud and it loads the plugin at the build time.
Is there a way to set it programmatically from the usage area?

Thank you

**Comment by wayne-christian** [comment]
Sorry to pick up on this, but can i clarify that phonegap build is supported? I have seen the npm, downloaded relevant files but can not find WikitudePlugin.js to change line 12 for a trial?
Thanks

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @wayne-christian ,
The license needs to be changed in the file `WikitudePlugin.js`. There you find the variable for the license key in the first lines.

Best regards,
Andreas

**Comment by wayne-christian** [comment]
Hi Andreas, sorry fif i am being blind, but where is the WikitudePlugin.js. I am assuming with phone gap build (adobe SAS) that we link to the npm in the nonfig and would usually add some info there. I have downloaded all of the cordova resources but cant see the WikitudePlugin.js anywhere. Even using the phonegap desktp app and the sample resources - there is no WikitudePlugin.js. do thi sneed to be downloaded and added manually?

Thanks

Wayne

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @wayne-christian,
The file I'm talking about is part of this repository.
I'm not very familiar with PhoneGap build - do you actually add the Wikitude Cordova plugin to your PhoneGap project locally or is this happening on the cloud build machine?

**Comment by wayne-christian** [comment]
I wanted to to use the gap build servers, but you can still upload your own files. I have started to build locally with PhoneGap. I could not find the relevant js file to add the key from the repo.

Kindest Regards

Wayne Christian
________________________________

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @wayne-christian,
It sounds very weird that you can't the file I was talking about. Can you send a screenshot of your IDE or provide a link to a project?

Best regards,
Andreas

**Comment by wayne-christian** [comment]
Hi Andreas. Sorry I found the file on GitHub. I didn’t read it properly. It is not included with the Cordova world examples. Phonegap desktop creates the pgday example and works fine, however I am struggling to get the Cordova world examples to work with phonegap. The camera works but the ar overlay does not. See attached. Are there any phonegap example of object tracking? Is the below error a path issue in the simpleindicies.js?

[Image]
Kindest Regards

Wayne Christian
________________________________
