### ISSUE TITLE
Add iOS 10 Support

### ISSUE THREAD

**Issue by pwasem** [Wikitude/wikitude-cordova-plugin#110]
I have just tested v5.1.4-3.2.1 under the first iOS 10 beta and unfortunately got this error when trying to open the plugin:

_This device does not support the requirements to perform 2D tracking. 
The iOS version on this device ('10.0') is not supported. Wikitude SDK requires iOS 6 or later._

**Comment by rakeshpalivela** [comment]
I am also facing issue in iOS 10 beta 2 version. It saying "The device is not compatible to access".

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi, we released a so called 'developer release' just a few days ago which fixes this issue. Geo AR will not work until the next developer release which will go live in the upcoming week.

[Developer release Android](http://wikitude-web-hosting.s3.amazonaws.com/sdk/developer-channel-releases/Android/WikitudeSDK_Android_5-2-0_2016-07-26_10-16-46.zip)
[Developer release iOS](http://wikitude-web-hosting.s3.amazonaws.com/sdk/developer-channel-releases/iOS/WikitudeSDK_iOS_5-2-0_2016-07-26_09-57-18.zip)

**Comment by sandroweb** [comment]
I have tested v.5.2.0 with iOS10 and v4.0.0 of Cordova iOS Engine, but when I have calling the startWorld() method, nothing happens, but on Android device, working normaly.

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi sandroweb,
[Here](http://wikitude-web-hosting.s3.amazonaws.com/sdk/support/forum/cordova_plugin_preview/Wikitude_Cordova_Plugin_5-3-0_3-3-0_2016-09-06_13-29-46.zip) is a download link for a pre-release version of our Cordova plugin that supports iOS 10. We're planning to make an update public available by end of this week/beginning of next week.

**Comment by pwasem** [comment]
thx for the update, i have just deployed it to my iOS 10 device and it works as expected!

**Comment by sandroweb** [comment]
I downloaded the pre-release version, but occured the same problem on iOS 10:
![image](https://cloud.githubusercontent.com/assets/260201/18749638/3e1c345a-80ae-11e6-9aee-7eb079f4889e.png)

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @sandroweb, did you add the `NSCameraUsageDescription` key to your application .plist file?

**Comment by sandroweb** [comment]
Thanks @AndreasSchacherbauerWikitude!

You need insert this at `plugin.xml`:
```
<config-file parent="NSCameraUsageDescription" target="*-Info.plist">
    <string>Type here your usage description</string>
</config-file>
```
