### ISSUE TITLE
WikitudePlugin.js missing cordova.define 

### ISSUE THREAD

**Issue by jdart** [Wikitude/wikitude-cordova-plugin#111]
In the latest release (5.2.0-3.3.0) WikitudePlugin.js seems to be missing an essential bit to make it work:
 
At the beginning: 
 
`cordova.define("com.wikitude.phonegap.WikitudePlugin.WikitudePlugin", function(require, exports, module) {`
And at the end
`});`
 
Maybe it's a new cordova convention to omit it, but in my case I had to hack up that file.

**Comment by AndreasSchacherbauerWikitude** [comment]
Are you installing our plugin with Plugman or the cordova command line tool? These lines should be added by those tools.

**Comment by jdart** [comment]
I am using plugman, i got things working, the problem was with a cordova hook causing an exception and preventing the plugin from being installed completely.
