### ISSUE TITLE
Android has an incorrect string comparison for checking WikitudeCordovaPluginLocalPathPrefix

### ISSUE THREAD

**Issue by timkim** [Wikitude/wikitude-cordova-plugin#112]
Hey there,

Testing out the new updates and I found that this particular line: https://github.com/Wikitude/wikitude-cordova-plugin/blob/master/src/android/WikitudePlugin.java#L487 is incorrect. Through my tests, I keep getting the wrong file path (i.e., not getting the WikitudeCordovaPluginLocalPathPrefix I defined in the `plugin.xml`). Pretty sure it should use the `equals()` to compare strings.

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi,
thx for mentioning it. It's already fixed in the master branch.
