### ISSUE TITLE
Error on all cloud recognitions

### ISSUE THREAD

**Issue by Geoffie** [Wikitude/wikitude-cordova-plugin#113]
I just ran the sample app and everything works well except the following worlds

2_CloudRecognition_2_ContinuousRecognitionVsOn-Click
2_CloudRecognition_3_UsingMetainformationInTheResponse

getting the following error

![image](https://cloud.githubusercontent.com/assets/8654757/17593299/bc6689bc-5fe5-11e6-80c2-8fde693b3c34.png)

So nothing shows up when i click on the down arrow. but when i click on the silver link on the side then this shows

setTimeout(function(){AR.om.getObjectForID(1).onRecognitionError(400, "{"code":400,"reason":"HEADER_PROPERTY_INVALID","message":"One or more header properties are invalid.","cause":[{"item":"X-Horizontal-FOV","value":"0"}],"moreInfo":"http://www.wikitude.com/developer/documentation/cloudrecognition"}");},0)

 this is some advice and assistance i got when asking for help from other devs

Hum... From this message, I assume that there is some kind of header error when your device try to access the API. But I don't know what's causing it.

Anyway, with the code that you copied on your last message, we can see that it's some code that tries to execute this onErrorRecognition callback:

onRecognitionError: function onRecognitionError(errorCode, errorMessage) {
    alert("error code: " + errorCode + " error message: " + JSON.stringify(errorMessage));
},
Except it seems to pass a value for errorMessage that's all messed up with the quotation mark, as you can see (I've trimmed the message up to the first quotation mark):

"{"code":400,"reason":"HEADER_PROPERTY_INVALID","message":"One or more header properties are invalid.","cause":[{"item":"X-Horizontal-FOV","value":"0"}],"moreInfo":"http://www.wikitude.com/developer/documentation/cloudrecognition"}");},0)
I think that it's what causing the Uncaught Syntax Error.
But it's code that I have no access to.

I think you should discuss this issue directly with the folks at Wikitude, sorry.

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi Geoffie,
We already have an updated version of our SDK available in our beta download section. Please replace the wikitudesdk.aar (for Android) or WikitudeSDK.framework (for iOS) in your existing Cordova project with the one you downloaded from our beta download section.
Here are the direct download links: [Android](http://wikitude-web-hosting.s3.amazonaws.com/sdk/developer-channel-releases/Android/WikitudeSDK_Android_5-2-0_2016-07-26_10-16-46.zip) [iOS](http://wikitude-web-hosting.s3.amazonaws.com/sdk/developer-channel-releases/iOS/WikitudeSDK_iOS_5-2-0_2016-07-26_09-57-18.zip)

**Comment by Geoffie** [comment]
Thank you so much. Works perfectly
