### ISSUE TITLE
50mb limit

### ISSUE THREAD

**Issue by jonvmp** [Wikitude/wikitude-cordova-plugin#117]
Please consider the maximum size of your plugin, it's greater than 50mb and that causes a problem with both appery.io and telerik.  The plugin can't be uploaded because of the 50mb size limit.
Your own page even recommends telerik:
https://www.wikitude.com/products/extensions/cordova-plugin-augmented-reality/

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @jonvmp,
With the release of our Wikitude SDK 7.0, we split the iOS library file in multiple files. Unfortunately they are still slightly above 50 MB, but there are almost no options left to reduce the file size even more, sorry.

Best regards,
Andreas
