### ISSUE TITLE
AR development using Cordova Error Build

### ISSUE THREAD

**Issue by bandeto45** [Wikitude/wikitude-cordova-plugin#120]
Hi, sir/mam, I am a first time in AR development using Cordova. When I run my project it could not proceed and display an error like below. How could I address that? I'm using Visual Studio 2017 for Cordova development and the version of Cordova is 6.3.1. Please help how do I address this situation.  

1>MSBUILD : cordova-build error : C:\Users\James\Documents\Visual Studio 2017\Projects\Wikitude\Wikitude\platforms\android\AndroidManifest.xml:18:5-74 Error:
1>MSBUILD : cordova-build error :  uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [:wikitudesdk:] C:\Users\James\Documents\Visual Studio 2017\Projects\Wikitude\Wikitude\platforms\android\build\intermediates\exploded-aar\wikitudesdk\AndroidManifest.xml
1>MSBUILD : cordova-build error :  Suggestion: use tools:overrideLibrary="com.wikitude.architectandlib" to force usage
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : Execution failed for task ':processDebugManifest'.

BUILD FAILED

Total time: 1.937 secs

1>MSBUILD : cordova-build error : > Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [:wikitudesdk:] C:\Users\Dexter Banastao\Documents\Visual Studio 2017\Projects\Wikitude\Wikitude\platforms\android\build\intermediates\exploded-aar\wikitudesdk\AndroidManifest.xml
1>MSBUILD : cordova-build error :  Suggestion: use tools:overrideLibrary="com.wikitude.architectandlib" to force usage
1>MSBUILD : cordova-build error : * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Command finished with error code 1: cmd /s /c ""C:\Users\James\documents\visual studio 2017\Projects\Wikitude\Wikitude\platforms\android\gradlew.bat" cdvBuildDebug -b "C:\Users\Dexter Banastao\documents\visual studio 2017\Projects\Wikitude\Wikitude\platforms\android\build.gradle" -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
1>MSBUILD : cordova-build error : Error: cmd: Command failed with exit code 1 Error output:

1>MSBUILD : cordova-build error : C:\Users\James\Documents\Visual Studio 2017\Projects\Wikitude\Wikitude\platforms\android\AndroidManifest.xml:18:5-74 Error:
1>MSBUILD : cordova-build error :  uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [:wikitudesdk:] C:\Users\James\Documents\Visual Studio 2017\Projects\Wikitude\Wikitude\platforms\android\build\intermediates\exploded-aar\wikitudesdk\AndroidManifest.xml
1>MSBUILD : cordova-build error :  Suggestion: use tools:overrideLibrary="com.wikitude.architectandlib" to force usage
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : Execution failed for task ':processDebugManifest'.
1>MSBUILD : cordova-build error : > Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [:wikitudesdk:] C:\Users\James\Documents\Visual Studio 2017\Projects\Wikitude\Wikitude\platforms\android\build\intermediates\exploded-aar\wikitudesdk\AndroidManifest.xml
1>MSBUILD : cordova-build error :  Suggestion: use tools:overrideLibrary="com.wikitude.architectandlib" to force usage
1>MSBUILD : cordova-build error : * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>MSBUILD : cordova-build error : Picked up _JAVA_OPTIONS: -Xmx512M

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @bandeto45,
Seems that your installed android sdk version is too old: `Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library`. Installing a newer version of the Android SDK should resolve the problem.
