### ISSUE TITLE
Wikitude 7 error when I add platform iOS

### ISSUE THREAD

**Issue by bukosabino** [Wikitude/wikitude-cordova-plugin#125]
I can execute this script in my terminal and this work fine: 

> source plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh

But, I have several problems when I try add platform iOS to my project.

**Reconstructing WikitudeSDK.framework content. In case this script fails, please contact Wikitude support.**

**error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified**

**fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...**

**Error: Hook failed with error code 1: /path-project/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh**

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @bukosabino,
I might misunderstand you, but you should not execute the script `configure_wikitude_sdk_framework.sh` yourself. It should be executed from the plugin installation process (cordova). 

Can you tell me your local project path? Maybe some whitespace in the path is messing up the script.

**Comment by bukosabino** [comment]
Hi Andreas,

this error are the output of:

> ionic platform add ios

This is my full path: /Users/bukosabino/projects/ionic2/escape-game/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh

PS: When I add android platform everything is ok.

**Comment by mryechkin** [comment]
I just ran into the exact same issue as well when trying to add the plugin to my Ionic application

**Comment by bukosabino** [comment]
Your system information:

Cordova CLI: 7.0.1 
Ionic Framework Version: 3.5.3
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 2.1.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.6 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.3.1 Build version 8E1000a

@AndreasSchacherbauerWikitude

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @all,
I create a new feature branch named `feature/additional_script_logging` which contains some logging. Somehow a Ionic environment leads to a failure in the script.
Please use the script from this branch and let me know the log output, thx!

**Comment by bukosabino** [comment]
Installing "com.wikitude.phonegap.WikitudePlugin" for ios


            Have fun using world's first AR plugin for PhoneGap. Visit http://www.wikitude.com/developer/documentation/phonegap for detailed documentation for the plugin.
            
            Make sure that you enter your Wikitude SDK trial license key in `WikitudePlugin.js` line 53. If you havent bought a license please visit http://www.wikitude.com/store.
            
            If you want to contribute to the open source project, please visit us at github, http://github.com/Wikitude
        


Running command: /Users/bukosabino/projects/ionic2/escape-game/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh /Users/bukosabino/projects/ionic2/escape-game


Reconstructing WikitudeSDK.framework content. In case this script fails, please contact Wikitude support.

final lipo command:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -create -output "./platforms/ios/TheEscapeGame/Plugins/com.wikitude.phonegap.WikitudePlugin/WikitudeSDK.framework"/WikitudeSDK

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...

Failed to install 'com.wikitude.phonegap.WikitudePlugin': Error: Hook failed with error code 1: /Users/bukosabino/projects/ionic2/escape-game/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @bukosabino,
Thx for running the first version of the debug script. It seems that the script is unable to find the `WikitudeSDK.framework`. For PhoneGap applications it's included three times within the project structure. Somehow it seems that this is different for Ionic projects.
Could you send me a demo project or a screenshot of the project structure so that I can see where the `WikitudeSDK.framework` is located?
I also updated the script one more time and added more logging. Could you run it again and send me the output again? THX!

**Comment by RafaelKr** [comment]
Hi @AndreasSchacherbauerWikitude,

the first problem I noticed is, that your script fails if you're using blanks in the name of your app.
```
Running command: "/Users/developer/Desktop/coding/My CDVApp/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh" "/Users/developer/Desktop/coding/My CDVApp"
Reconstructing WikitudeSDK.framework content. In case this script fails, please contact Wikitude support.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: ./platforms/ios/My (No such file or directory)
Failed to install 'com.wikitude.phonegap.WikitudePlugin': Error: Hook failed with error code 1: /Users/developer/Desktop/coding/My CDVApp/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:232:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Error: Hook failed with error code 1: /Users/developer/Desktop/coding/My CDVApp/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh
```

This can be solved by modifying your script like this:
```bash
#!/bin/sh
#
#  configure_wikitude_sdk_framework.sh
#
#  Created by Andreas Schacherbauer on 07/24/17.
#
#

set -e

# Because the WikitudeSDK.framework contains a file larger 100 MB, this file is split up into multiple smaller ones.
# Once the Wikitude Cordova plugin is installing, these files are combined again into a single file.
# This is needed because linking the final application would fail otherwise.

echo 'Reconstructing WikitudeSDK.framework content. In case this script fails, please contact Wikitude support.'

# Find all occurences of the WikitudeSDK.framework in the Cordova application directory structure (The current working directory is the project root directory)
find . -type d -name "WikitudeSDK.framework" | while read dir; do

  # Inside the WikitudeSDK.framework, all WikitudeSDK-* files need to be combined into a single one again
  SINGLE_ARCHITECTURE_SLICES_PATHS="$(find "${dir}" -name "WikitudeSDK-*" -exec echo -n '"{}" ' \;)"
  SINGLE_ARCHITECTURE_SLICES_PATHS=$(echo "$SINGLE_ARCHITECTURE_SLICES_PATHS" | sed 's|/Plugin |/Plugin\\ |g') # The project path might contain blanks. This should prepare the paths to be usable by `lipo`

  # ... this is done using `lipo`
  LIPO_COMMAND="$(xcrun --sdk iphoneos --find lipo) -create $SINGLE_ARCHITECTURE_SLICES_PATHS -output \"$dir/WikitudeSDK\""
  eval $LIPO_COMMAND

  # After lipo is done, all WikitudeSDK-* files can be deleted
  RM_COMMAND="rm $SINGLE_ARCHITECTURE_SLICES_PATHS"
  eval $RM_COMMAND
done
```

Sorry that I didn't send a PR, have no time for that atm. I modified the find command in `SINGLE_ARCHITECTURE_SLICES_PATHS`. Also I think that you unintentionally misplaced a quote-sign in the output-path in your `LIPO_COMMAND`, I also fixed that.


After that I get the following output, no difference for Ionic or plain cordova:
```
Reconstructing WikitudeSDK.framework content. In case this script fails, please contact Wikitude support.
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...
Failed to install 'com.wikitude.phonegap.WikitudePlugin': Error: Hook failed with error code 1: /Users/developer/Desktop/coding/My CDVApp/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:232:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Error: Hook failed with error code 1: /Users/developer/Desktop/coding/My CDVApp/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh
```

In the Ionic-App the `WikitudeSDK.framework`is located at `./platforms/ios/My IonicApp/Plugins/com.wikitude.phonegap.WikitudePlugin/WikitudeSDK.framework`. This is the same as for cordova. So I think the problem isn't related to Ionic.

If you have any questions feel free to contact me.

**Comment by bukosabino** [comment]
Hi @AndreasSchacherbauerWikitude 

The new output:

Running command: /Users/bukosabino/projects/ionic2/escape-game/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh /Users/bukosabino/projects/ionic2/escape-game

Reconstructing WikitudeSDK.framework content. In case this script fails, please contact Wikitude support.
/Users/bukosabino/projects/ionic2/escape-game

Start searching for the WikitudeSDK.framework in the project structure

   Found a WikitudeSDK.framework in the following directory

./platforms/ios/TheEscapeGame/Plugins/com.wikitude.phonegap.WikitudePlugin/WikitudeSDK.framework

final lipo command:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -create -output "./platforms/ios/TheEscapeGame/Plugins/com.wikitude.phonegap.WikitudePlugin/WikitudeSDK.framework"/WikitudeSDK

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...


The screenshot:

![screen shot 2017-08-10 at 12 52 00](https://user-images.githubusercontent.com/4375209/29168453-3a38dac2-7dcf-11e7-89bb-5fb71c8237fa.png)

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @bukosabino,
Thx again for running the script and sending the screenshot. The screenshot actually shows something very interesting. In there, the content of the WikitudeSDK.framework only shows one file called `WikitudeSDK`. I expect this one to exist after the script was running successfully, but not before. After cloning the repo from GitHub, `WikitudeSDK` should be split up into five files, all called `WikitudeSDK-*architecture*`. 

My question now: Which command did you use to add the Wikitude Plugin to your project? Did you try to build the [Wikitude Cordova example application](https://github.com/Wikitude/wikitude-cordova-plugin-samples)?

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @RafaelKr,
Thx for your suggestions! I will add them soon.
I just have the same question to you as to @bukosabino: Which command did you use to add the Wikitude Cordova plugin to your project?
Could you also send me a screenshot of the Wikitude Cordova plugin directory structure (mainly interested in the `WikitudeSDK.framework`) after cloning from GitHub/when the command failed.

It seems that the `limo` command is missing a parameter because `find` is unable to find the files called `WikitudeSDK-*architecture*`. The `.framework` content should look like [this](https://github.com/Wikitude/wikitude-cordova-plugin/tree/master/src/ios/WikitudeSDK.framework) before the script is running.

Thx for your help so far!

**Comment by bukosabino** [comment]
I dont use any command, I copy and paste the plugin in plugin folder

![screen shot 2017-08-11 at 11 46 06](https://user-images.githubusercontent.com/4375209/29208525-b94ead62-7e8a-11e7-9160-f81119caedd7.png)

**Comment by AndreasSchacherbauerWikitude** [comment]
but how did you added the Wikitude Cordova plugin initially @bukosabino? You need to call something like `cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git` to get all the files initially.

**Comment by bukosabino** [comment]
Ok, this was my problem. I can add ios platform now!

**Comment by bukosabino** [comment]
Sorry @AndreasSchacherbauerWikitude 

`cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git` works fine for me but this is not ideal way to work with Ionic, then I need to do:

`ionic plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git`

When I do this, I get this output:

Running command: /Users/bukosabino/projects/ionic2/escape-game/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh /Users/bukosabino/projects/ionic2/escape-game

Reconstructing WikitudeSDK.framework content. In case this script fails, please contact Wikitude support.

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: 
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...
Error: Hook failed with error code 1: /Users/bukosabino/projects/ionic2/escape-game/plugins/com.wikitude.phonegap.WikitudePlugin/scripts/configure_wikitude_sdk_framework.sh

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @all,
I just published a new version of the merge script. It's available in the `additional_script_logging` feature branch. 
Please let me know if you continue encounter issues with this one.

Best regards,
Andreas

**Comment by bukosabino** [comment]
Hi @AndreasSchacherbauerWikitude,
This new version is genial. The error disappear!

Also, I have tested the @RafaelKr improvement, this allow spaces in the path:
`SINGLE_ARCHITECTURE_SLICES_PATHS="$(find` "${dir}" -name "WikitudeSDK-*" -exec echo -n '"{}" ' \;)"`

I have sended a pull request:
https://github.com/Wikitude/wikitude-cordova-plugin/pull/127

Kind regards,

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @bukosabino,
Thx for the pull request. We just published the new script with your changes as new release.

Best regards,
Andreas
