### ISSUE TITLE
IOS Publish failed

### ISSUE THREAD

**Issue by jeewankarki** [Wikitude/wikitude-cordova-plugin#126]
Hi,

When i run the app then showing error in below line.

Please Find reference screenshot attachment.  

![screen shot 1939-05-27 at 7 44 43 pm](https://user-images.githubusercontent.com/6650405/29460697-867da980-8446-11e7-8be1-52e101166e98.png)

/**
 *
 * The WTRenderingAPI can be used choose which OpenGL version should be used by the SDK for rendering
 *
 */
WT_DEPRECATED_SINCE(7.0.0, "Use WTRenderingConfiguration instead.")
typedef NSString * WTRenderingAPI NS_EXTENSIBLE_STRING_ENUM;

Thanks,
Jeewan

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @jeewankarki,
Which version of Xcode are you using?
I guess you didn't modified the Wikitude Cordova plugin in any way before you encountered this problem?!

Best regards,
Andreas

**Comment by vdcg444** [comment]
I was having the same issue when starting a new cordova+wikitude project. I did what Xcode suggest to do and modified that line `typedef NSString * WTRenderingAPI; NS_EXTENSIBLE_STRING_ENUM;`. :/

**Comment by vdcg444** [comment]
I was having the same issue even when starting a new cordova+wikitude project. I did what Xcode suggest to do and modified that line `typedef NSString * WTRenderingAPI; NS_EXTENSIBLE_STRING_ENUM;` in WTWikitudeTypes.h file and that fix the problem. :confused:
Xcode Version : Version 7.3 (7D175)

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @vdcg444,
Is there a particular reason why you use Xcode 7.x? It's kind of old...

Best regards,
Andreas

**Comment by vdcg444** [comment]
I know! @AndreasSchacherbauerWikitude, I was in a hurry then, that's why I didn't upgrade my job's mac. Going to try with the latest version now, thank you!

**Comment by AndreasSchacherbauerWikitude** [comment]
Perfect, please let me know if it's fine with Xcode 8.x or 9.x (beta)
