### ISSUE TITLE
SDKKey becomes invalid  

### ISSUE THREAD

**Issue by NAOZANS** [Wikitude/wikitude-cordova-plugin#129]
Since I get a new Mac Book Pro,
Using Xcode8.3.3 and phonegap7.0.1, 
However I set license key at SDKKey in 2 files of the latest wikitude-cordova-plugin the same as before, "SDKKey is missing" is shown on screen.

Bundle Identify is right as well.

Let me know where I should check for next steps.

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @NAOZANS,
I guess the watermark you see says 'LICENSE KEY MISSING', am I right?
This means that either no key is given (like the SDK method `-setLicenseKey` is not called (which happens within the Wikitude Cordova Plugin, so I assume this is fine)) or the bundle identifier is wrong. In case the bundle identifier is wrong, there are some log messages written to the Xcode console, explaining which bundle identifier are licensed and what is the current one.
Can you please check the Xcode console output and get back to me afterwards?

thx,
Andreas

**Comment by NAOZANS** [comment]
Thanks for your comment.
I heard this problem in order to "SDK version" from Wikitude support morning.
Therefore, I download older plugin and install, my app work right, right now. 

So please close...
