### ISSUE TITLE
Error uploading app to iTunes store due to framework issues

### ISSUE THREAD

**Issue by timkim** [Wikitude/wikitude-cordova-plugin#130]
So I'm trying to upload the PhoneGap Developer App to the iTunes store but I keep getting rejected in the process. It appears that there are some wikitude framework issues that I'm unfamiliar with and unsure how to solve. 

I've tried building with xcode 8.3.3 and even 9 but I still get the same issues. Attached is an image showing the errors I'm getting when I try to deliver my app. 
<img width="1069" alt="wikitude-framework" src="https://user-images.githubusercontent.com/57922/30672982-c2df1e98-9e24-11e7-9680-94d1df34fa60.png">

**Comment by timkim** [comment]
The PhoneGap Developer App Repo: https://github.com/phonegap/phonegap-app-developer
My custom wikitude plugin repo: https://github.com/timkim/wikitude-cordova-plugin

To note, I got around that annoying install issue where the plugin was too large by publishing it to npm under its own name: https://www.npmjs.com/package/wikitude-plugin-phonegap-dev-app which points to the repo:  https://github.com/timkim/wikitude-cordova-plugin.

**Comment by nilebma** [comment]
@timkim : about this problem, you should see this thread on wikitude forum : https://support.wikitude.com/support/discussions/topics/5000084342

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @all,
We released a minor update to our SDK just recently. We now have some scripts included that can be used to remove simulator architectures. The process is documented [here](http://www.wikitude.com/external/doc/documentation/latest/ios/setupguideios.html#removing-simulator-architectures-for-app-store-submissions).

Best regards,
Andreas

**Comment by timkim** [comment]
Hi again,

So I tried to upgrade to 7.1.0 but my submissions were being rejected because parts of the wikitude framework (some scripts for piecing the framework back together) weren't being code signed. This generated an error error itms-90035 from Application Loader. 

I finally got it the app to submit to the store successfully by downgrading to 7.0.0 and using the stackoverflow solution from @nilebma's link.

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @timkim,
You should be able to use our SDK 7.1.0. Simply put the scripts, like described in my previous post, in the final Xcode project and archive the app.

How did you generate the .app bundle for the App Store?

Best regards,
Andreas

**Comment by timkim** [comment]
Hi @AndreasFoetschlWikitude 

Ya, I tried but I kept on running into errors. Not sure what the deal was but, I managed to make it work. 

Here are the steps:
- built the ios platform using our own scripts, but essentially boils down to `cordova build ios --release`
- open up xCode and set the build scheme to generic ios device
- archive
- open up Organiser and export
- use Application Loader to send .ipa file to itunes
- during the validation phase of this process is where it broke for me

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @timkim,
I guess you're missing just one step: After your second step, add the Wikitude strip script to the Xcode projects 'Build Phases' like described [here](http://www.wikitude.com/external/doc/documentation/latest/ios/setupguideios.html#removing-simulator-architectures-for-app-store-submissions).

**Comment by timkim** [comment]
Ahh, well I'll try that giving a go for the next release of the dev app.

**Comment by AndreasSchacherbauerWikitude** [comment]
ok, great! let us know if you encounter any problems the next time you submit your app
