### ISSUE TITLE
Wikitude intro animation + "powered by Wikitude" logo

### ISSUE THREAD

**Issue by SebLambla** [Wikitude/wikitude-cordova-plugin#131]
Hello,

We're planning to buy a license of Wikitude SDK to use the Cordova plugin, but can you confirm that a full license will allow us to get rid of the "powered by Wikitude" logo, as well as the introduction animation (the big Wikitude logo, fading out on initialization)?

Thanks

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @SebLambla,
The answer to your question is short and simple: YES. Buying a license will remove the logo and the splash animation at SDK launch.

Best regards,
Andreas

**Comment by SebLambla** [comment]
Perfect, thanks!
