### ISSUE TITLE
CordovaError: Failed to fetch plugin

### ISSUE THREAD

**Issue by vicung** [Wikitude/wikitude-cordova-plugin#134]
I found this older issue #https://github.com/Wikitude/wikitude-cordova-plugin/issues/122 where a few people seem to have a similar problem, but not exactly the same, so I'm opening a new one and hope that's ok.

When trying to add the wikitude plugin to my local cordova project via command line
cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git
 I encounter the following error, see full debug.log attached 
[2018-08-02T13_25_16_224Z-debug.log](https://github.com/Wikitude/wikitude-cordova-plugin/files/2253681/2018-08-02T13_25_16_224Z-debug.log):

Command finished with error code 1: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install https://github.com/Wikitude/wikitude-cordova-plugin.git --production --save"
(node:17384) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/Wikitude/wikitude-cordova-plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/Wikitude/wikitude-cordova-plugin.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/Wikitude/wikitude-cordova-plugin.git/': error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
npm ERR!
npm ERR! exited with error code: 128

I'm on Windows 10, working with Cordova 8.0.0, Android 7.1.0 and my company requires me to work behind a proxy, so I have set up some system environment variables and didn't have any problems with other cordova plugins yet.

I have already tried downloading the Wikitude-Cordova-SDK from the Wikitude Website, adding the folders to my projects plugin directory and changing the config.xml accordingly, but when trying to run the app I get the error "Failed to restore plugin "com.wikitude.phonegap.WikitudePlugin"...". I would really appreciate some help.

**Comment by danielguttenberg** [comment]
You can just download the plugin from github as a zip, extract it and then add the plugin from these local files using **cordova plugin add <THE_LOCAL_PATH>** to circumvent any network related issues.

**Comment by vicung** [comment]
That worked, thank you very much!
