### ISSUE TITLE
cordova image not found

### ISSUE THREAD

**Issue by videmort** [Wikitude/wikitude-cordova-plugin#136]
I'm getting this error on xCode launching the app

dyld: Library not loaded: @rpath/WikitudeSDK.framework/WikitudeSDK
  Referenced from: /var/containers/Bundle/Application/521B55B8-CDA6-4F39-8FE8-D812D3AC03D9/WikitudeIonic3StarterApp.app/WikitudeIonic3StarterApp
  Reason: image not found
(lldb)

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @videmort ,
Did you update your Cordova and Cordova-iOS installations to the latest available versions? They usually add additional dependencies correctly in Xcode.
You can manually fix this by adding the WikitudeSDK framework to the 'Embedded Binaries' section in the targets General tab.
