### ISSUE TITLE
Error: Failed to fetch plugin https://github.com/Wikitude/wikitude-cordova-plugin.git via registry.

### ISSUE THREAD

**Issue by joe-scotto** [Wikitude/wikitude-cordova-plugin#137]
I've been trying to install the plugin on a fresh Ionic project for over an hour now. I've done this once before on an existing project without issues. I get through the entire process except when I go to install the plugin is where it errors out...

I get the following once running `cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git`

```
Error: Failed to fetch plugin https://github.com/Wikitude/wikitude-cordova-plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

Any ideas as to why this would be happening?

My ionic info is as follows:
```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/Users/jscotto/.nvm/versions/node/v6.11.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : android 6.2.3, ios 4.4.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 4 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v6.11.3 (/Users/jscotto/.nvm/versions/node/v6.11.3/bin/node)
   npm        : 3.10.10
   OS         : macOS High Sierra
   Xcode      : Xcode 9.0 Build version 9A235
```

**Comment by toddhalfpenny** [comment]
This is related to #122 as far as I can see.
I was able to install the plugin by downloading the cordova download from https://www.wikitude.com/download-wikitude-sdk-for-cordova/, unzipping and then referencing the local path in my command, like this; `https://www.wikitude.com/download-wikitude-sdk-for-cordova/ <PATH-TO-LOCAL-WIKITUDE>`

**Comment by pnagele** [comment]
Please have a look at the resolution described in #122, which should fix this one as well (specifying a version).
