### ISSUE TITLE
update wikitude-cordova-plugin version on npm to 8.9.1

### ISSUE THREAD

**Issue by gabides** [Wikitude/wikitude-cordova-plugin#143]
Platform: iOS
Wikitude plugin version: 8.9.0
Cordova version: 9.0.0

With plugin version 8.9.0, the AR experience crashes when launched on ios. Problem is fixed on 8.9.1 but this version is not available on npm. Is it possible to publish 8.9.1 on npm ?

https://www.npmjs.com/package/com.wikitude.phonegap.wikitudeplugin

Thanks

**Comment by pnagele** [comment]
Sorry for the delay here - 8.9.1 has just been published on npm

`+ com.wikitude.phonegap.wikitudeplugin@8.9.1`

Usually takes a little on npm side to udpate.
