### ISSUE TITLE
Integrating with SDK Plugins API

### ISSUE THREAD

**Issue by FREEZX** [Wikitude/wikitude-cordova-plugin#144]
Hi,
I'm attempting to develop a cordova application that uses a native plugin that uses openCV.

The plugins page states: "Plugins are written in C++, Java or ObjC and can communicate both with the JavaScript API and the Native API.". I assume cordova uses Javascript API referenced, but i couldn't find any examples or documentation on how i should approach this.

Are there any examples or docs available for integrating the plugin API with cordova?

**Comment by danielguttenberg** [comment]
Unfortunately, our JavaScript extensions, including Cordova, do not support plugins. You will have to use the regular JavaScript SDK for that.
