### ISSUE TITLE
Submission to Phonegap Build or plugins.cordova.io

### ISSUE THREAD

**Issue by robinbonnes** [Wikitude/wikitude-cordova-plugin#67]
Recently Phonegap Build updated their plugin infrastructure and they are allowing all plugins even with native code.

Is there any change this plugin will be submitted?

Thanks,

Robin

**Comment by pnagele** [comment]
Hi Robin,

sorry for the late reply and thx for your message. I'm looking into this early next week and tell you more on our plans.

Thx again

Phil

**Comment by robinbonnes** [comment]
Hello pnagele,

Maybe this is possible from now on due to the move to NPM: http://phonegap.com/blog/2015/05/26/npm-plugins-available/

**Comment by pnagele** [comment]
Please see our plugin published on npm:
[https://www.npmjs.com/package/com.wikitude.phonegap.wikitudeplugin](https://www.npmjs.com/package/com.wikitude.phonegap.wikitudeplugin)
