### ISSUE TITLE
Build fail with Cordova 4.0.0 and Crosswalk plugin

### ISSUE THREAD

**Issue by logicweb** [Wikitude/wikitude-cordova-plugin#76]
I've just updated to cordova 4.0.0 and followed the instructions to use the crosswalk webview https://github.com/MobileChromeApps/cordova-plugin-crosswalk-webview
Without wikitude everything is fine. Installing the plugin via CLI cordova plugin add https://github.com/Wikitude/wikitude-phonegap.git is fine also.
When I run the build the following errors show up:

/Users/mt/dev/workspace/my_project/platforms/android/src/com/wikitude/phonegap/WikitudePlugin.java:754: error: cannot find symbol
                        ((CordovaWebView)rootView).clearFocus();
                                                  ^
  symbol:   method clearFocus()
  location: interface CordovaWebView
/Users/mt/dev/workspace/my_project/platforms/android/src/com/wikitude/phonegap/WikitudePlugin.java:770: error: method handleResume in interface CordovaWebView cannot be applied to given types;
                        ((CordovaWebView)rootView).handleResume(true, true);
                                                  ^
  required: boolean
  found: boolean,boolean
  reason: actual and formal argument lists differ in length
/Users/mt/dev/workspace/my_project/platforms/android/src/com/wikitude/phonegap/WikitudePlugin.java:771: error: cannot find symbol
                        ((CordovaWebView)rootView).clearFocus();
                                                  ^
  symbol:   method clearFocus()
  location: interface CordovaWebView
/Users/mt/dev/workspace/my_project/platforms/android/src/com/wikitude/phonegap/WikitudePlugin.java:772: error: cannot find symbol
                        ((CordovaWebView)rootView).requestFocus();
                                                  ^
  symbol:   method requestFocus()
  location: interface CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
:compileArmv7DebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.369 secs

/Users/mt/dev/workspace/my_project/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/mt/dev/workspace/my_project/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/mt/dev/workspace/my_project/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/mt/dev/workspace/my_project/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/mt/dev/workspace/my_project/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
M

**Comment by simonfriesenbichler** [comment]
Hi,

Crosswalk is currently not supported by the Wikitude Cordova plugin. At the moment there are no plans to support Crosswalk in the future.

Thank you and best regards,
Simon

**Comment by GHz** [comment]
I've got exactly the same error without any use of crosswalk. 

I've just runned the script for android and when I tried to run on a device :

```
/Users/helpymac/Development/build/platforms/android/src/com/wikitude/phonegap/WikitudePlugin.java:754: cannot find symbol
symbol  : method clearFocus()
location: interface org.apache.cordova.CordovaWebView
			((CordovaWebView)rootView).clearFocus();
			                          ^
/Users/helpymac/Development/build/platforms/android/src/com/wikitude/phonegap/WikitudePlugin.java:770: handleResume(boolean) in org.apache.cordova.CordovaWebView cannot be applied to (boolean,boolean)
			((CordovaWebView)rootView).handleResume(true, true);
			                          ^
/Users/helpymac/Development/build/platforms/android/src/com/wikitude/phonegap/WikitudePlugin.java:771: cannot find symbol
symbol  : method clearFocus()
location: interface org.apache.cordova.CordovaWebView
			((CordovaWebView)rootView).clearFocus();
			                          ^
/Users/helpymac/Development/build/platforms/android/src/com/wikitude/phonegap/WikitudePlugin.java:772: cannot find symbol
symbol  : method requestFocus()
location: interface org.apache.cordova.CordovaWebView
			((CordovaWebView)rootView).requestFocus();
			                          ^
4 errors
98 warnings
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.503 secs

/Users/helpymac/Development/build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/helpymac/Development/build/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/helpymac/Development/build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
ERROR running one or more of the platforms: Error: /Users/helpymac/Development/build/platforms/android/cordova/run: Command failed with exit code 1
You may not have the required environment or OS to run this project
```

**Comment by GHz** [comment]
If I comment these 4 lines. It Works.

**Comment by simonfriesenbichler** [comment]
Hi GHz,

you are right, Cordova 5 introduced the same problem. This problem is fixed, in the current version of our plugin released tuesday.

Best Regards,
Simon

**Comment by GHz** [comment]
Nice. Thanks for the quick support.
