### ISSUE TITLE
HTML Architecture File Not Loading

### ISSUE THREAD

**Issue by laurayco** [Wikitude/wikitude-cordova-plugin#81]
When executing this code:

``` javascript
this.app.wikitudePlugin._onARchitectWorldLaunchedCallback = (function () {
  console.log("Launched:", arguments);
});

this.app.wikitudePlugin._onARchitectWorldFailedLaunchingCallback = (function () {
  console.log("Launch Error:", arguments);
});

this.app.wikitudePlugin.setOnUrlInvokeCallback(function () {
  console.log("Url Invoke:", arguments);
});

this.app.wikitudePlugin.loadARchitectWorld("www/wikitude/world.html");
```

The expected result would be a Wikitude activity loading the HTML file in "www/wikitude/world.html". This doesn't happen, as far as I can tell. The "_onARchitectWorldLaunchedCallback" handler does get called, and there is a Wikitude activity launched. However, when inspecting the HTML using Chrome's dev tools, the body, and head elements are empty and the only ones in the HTML element at all. There is also an error about "AR" being undefined.

![Chrome Inspector](http://i.snag.gy/YPO43.jpg)

![AR Undefined](http://i.snag.gy/ky1fL.jpg)

I have verified that these files are in fact in the root of the application zip folder.

Here is the world.html file in use.

``` html
<!DOCTYPE html>

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta content="width=device-width,initial-scale=1,maximum-scale=5,user-scalable=yes" name="viewport">
    <link rel="stylesheet" href="css/style.css">
    <script src="architect://architect.js"></script>
  </head>
 <body>
    <span>HELLO?</span>
    <script type="text/javascript" src="js/index.js"></script>
  </body>
</html>
```

And the index.js in use.

``` javascript
var World = (function () {
  this.init_world = (function () {
      AR.context.services.sensors = false;
      console.log("INIT");
      AR.logger.activateDebugMode();
      this.tracker = new AR.ClientTracker("assets/magazine.wtc", {
        onLoaded: this.on_world_ready
      });
      this.weatherWidget = new AR.HtmlDrawable({
        uri: "./overlay.html"
      }, 0.25, {
        viewportWidth: 320,
        viewportHeight: 100,
        backgroundColor: "#FFFFFF",
        offsetX: +0.36,
        offsetY: 0.5,
        horizontalAnchor: AR.CONST.HORIZONTAL_ANCHOR.RIGHT,
        verticalAnchor: AR.CONST.VERTICAL_ANCHOR.TOP,
        clickThroughEnabled: true,
        allowDocumentLocationChanges: false,
        onDocumentLocationChanged: function onDocumentLocationChangedFn(uri) {
          AR.context.openInBrowser(uri);
        }
      }
    );
    this.trackable = new AR.Trackable2DObject(this.tracker, "*", {
      drawables: {
        cam: this.weatherWidget
      }
    })
  }).bind(this);
  this.on_world_ready = (function () {}).bind(this);
  return this;
});

console.log(window);
World().init_world();
```

I'm using the cordova plugin, and testing on Android - my best guess is that there might be an issue getting the correct HTML file loaded? I thought there might be something obvious I'm missing here, but I feel like my code pretty closely models the code provided in the samples.

**Comment by mislitzer** [comment]
Hi, I am write you because I have the same problem now. :)
I have included the architect file but in the console I get error.

Have you fixed the error meanwhile?

Nice greets

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi mislitzer, we're not aware of any issues in the current Cordova plugin. I assume you run the application on an iOS or Android device and not in a simulator/desktop browser?

Did you try out our Cordova example application? It should explain in detail how to use our Cordova plugin and our SDK itself.

**Comment by thekingrenz23** [comment]
hi i have the same problem i followed the documentation and it came to this same problem also i run the app on a android
`var app = {

    // Url/Path to the augmented reality experience you would like to load
    arExperienceUrl: "www/experience/index.html",
    // The features your augmented reality experience requires, only define the ones you really need
    requiredFeatures: [ "2d_tracking", "geo" ],
    // Represents the device capability of launching augmented reality experiences with specific features
    isDeviceSupported: false,
    // Additional startup settings, for now the only setting available is camera_position (back|front)
    startupConfiguration:
    {
        "camera_position": "back"
    },
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    onDeviceReady: function() {
        app.wikitudePlugin = cordova.require("com.wikitude.phonegap.WikitudePlugin.WikitudePlugin");
        app.wikitudePlugin.isDeviceSupported(app.onDeviceSupported, app.onDeviceNotSupported, app.requiredFeatures);
    },
    // Callback if the device supports all required features
    onDeviceSupported: function() {
        app.wikitudePlugin.loadARchitectWorld(
            app.onARExperienceLoadedSuccessful,
            app.onARExperienceLoadError,
            app.arExperienceUrl,
            app.requiredFeatures,
            app.startupConfiguration
        );
    },
    // Callback if the device does not support all required features
    onDeviceNotSupported: function(errorMessage) {
        alert(errorMessage);
    },
    // Callback if your AR experience loaded successful
    onARExperienceLoadedSuccessful: function(loadedURL) {
        /* Respond to successful augmented reality experience loading if you need to */
		alert("Pwede na tsong");
    },
    // Callback if your AR experience did not load successful
    onARExperienceLoadError: function(errorMessage) {
        alert('Loading AR web view failed: ' + errorMessage);
    }

};

app.initialize();`

![49708613_386996188771355_4210957615431155712_n](https://user-images.githubusercontent.com/24559541/50569888-5c018580-0d27-11e9-8640-bbf65c81d58d.png)
