### ISSUE TITLE
Compatibility with Bitcode in Xcode 7/iOS 9

### ISSUE THREAD

**Issue by grayxr** [Wikitude/wikitude-cordova-plugin#88]
Please make this plugin compatible with bitcode enabled in Xcode 7/iOS 9 - thanks.

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi, have you tried the latest version from our master branch? It should be compatible with Xcode 7, iOS 9 and Bitcode.

**Comment by jamesgrayillustration** [comment]
@AndreasSchacherbauerWikitude Hi, I believe I have, here is the error I'm getting:

```
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/GrayMidtown.app/GrayMidtown normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: xcconfig,/Users/james/Code/midtown/platforms/ios/cordova/build-debug.xcconfig,-project,GrayMidtown.xcodeproj,ARCHS=i386,-target,GrayMidtown,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/james/Code/midtown/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/james/Code/midtown/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/james/Code/midtown/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/james/Code/midtown/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by ehabmashraf** [comment]
I am facing the same issue when creating a new phonegap project after updating to xcode7 and then trying the command "phonegap build ios", Yet older project seems to run fine

**Comment by ehabmashraf** [comment]
I was able to generate an error from the xcode itself

ld: '/Users/repixels/Desktop/Augmented Reality/AugmentedReality/platforms/ios/Sunny Discover/Plugins/com.wikitude.phonegap.WikitudePlugin/libWikitudeSDK.a(WTOpenGLESExtensionManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by ktunex** [comment]
did you already solve the problem?

**Comment by ktunex** [comment]
I am facing the same issue.

**Comment by ehabmashraf** [comment]
Not yet , But I am working with the earlier version of iOS and closed the
bitcode and it seems to work just fine.

On Thursday, October 22, 2015, ktunex <notifications@github.com> wrote:

> I am facing the same issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wikitude/wikitude-cordova-plugin/issues/88#issuecomment-150170106>
> .
>


-- 
Sent from Gmail Mobile

Ehab M.Ashraf
Junior Creative and Technical Director - Fuze communications int. Ltd.
Bs in Computer Science -
Misr International University
📞 +201146101091

**Comment by sterlingsolutions** [comment]
Try disabling Bitcode in the Build Options in Xcode

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi, the Wikitude SDK now supports Bitcode ([Version 7.0.0](http://www.wikitude.com/external/doc/documentation/latest/ios/changelog.html#wikitude-sdk-700)). Please let us know if you still encounter Bitcode related issues, thx!
