### ISSUE TITLE
Phonegap iOS9 Support | Bitcode Issue

### ISSUE THREAD

**Issue by repixels** [Wikitude/wikitude-cordova-plugin#89]
After installing xcode 7.0, Phonegap produces an error when trying to build the project for a iOS platform.

Building project  : /Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/SunnyDiscover.xcodeproj

```
Configuration : Debug

Platform      : emulator
```

Build settings from command line:
    ARCHS = i386

```
CONFIGURATION_BUILD_DIR = /Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/build/emulator

SDKROOT = iphonesimulator9.0
SHARED_PRECOMPS_DIR = /Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/build/sharedpch

VALID_ARCHS = i386
```

Build settings from configuration file '/Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/cordova/build-debug.xcconfig':

```
CODE_SIGN_IDENTITY = iPhone Developer

CODE_SIGN_RESOURCE_RULES_PATH = $(SDKROOT)/ResourceRules.plist
```

=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET SunnyDiscover OF PROJECT SunnyDiscover WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution Copy\ www\ directory build/SunnyDiscover.build/Debug-iphonesimulator/SunnyDiscover.build/Script-304B58A110DAC018002A0835.sh
    cd "/Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios"
    /bin/sh -c \"/Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/SunnyDiscover.build/Debug-iphonesimulator/SunnyDiscover.build/Script-304B58A110DAC018002A0835.sh\"

ProcessInfoPlistFile build/emulator/SunnyDiscover.app/Info.plist SunnyDiscover/SunnyDiscover-Info.plist
    cd "/Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-infoPlistUtility /Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/SunnyDiscover/SunnyDiscover-Info.plist -genpkginfo /Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/emulator/SunnyDiscover.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/SunnyDiscover.build/Debug-iphonesimulator/SunnyDiscover.build/MainViewController-PartialInfo.plist -o /Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/emulator/SunnyDiscover.app/Info.plist

Ld build/emulator/SunnyDiscover.app/SunnyDiscover normal i386
    cd "/Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios"
    export IPHONEOS_DEPLOYMENT_TARGET=7.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/emulator -L/Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/SunnyDiscover/Plugins/com.wikitude.phonegap.WikitudePlugin -F/Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/emulator -filelist /Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/SunnyDiscover.build/Debug-iphonesimulator/SunnyDiscover.build/Objects-normal/i386/SunnyDiscover.LinkFileList -mios-simulator-version-min=7.1 -Xlinker -objc_abi_version -Xlinker 2 -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/emulator/libCordova.a -framework CoreGraphics -framework MobileCoreServices -lWikitudeSDK -lWikitudeSDK_simulator -framework Accelerate -framework AVFoundation -framework CFNetwork -framework CoreLocation -framework CoreMedia -framework CoreMotion -framework CoreText -framework CoreVideo -framework Foundation -framework MediaPlayer -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -framework UIKit -lc++ -lz -Xlinker -dependency_info -Xlinker /Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/SunnyDiscover.build/Debug-iphonesimulator/SunnyDiscover.build/Objects-normal/i386/SunnyDiscover_dependency_info.dat -o /Users/repixels/Desktop/Sunny/Phonegap\ Project/SunnyDiscover/platforms/ios/build/emulator/SunnyDiscover.app/SunnyDiscover

ld: warning: ignoring file /Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/SunnyDiscover/Plugins/com.wikitude.phonegap.WikitudePlugin/libWikitudeSDK.a, missing required architecture i386 in file /Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/SunnyDiscover/Plugins/com.wikitude.phonegap.WikitudePlugin/libWikitudeSDK.a (3 slices)
Undefined symbols for architecture i386:
  "wikitude::sdk_foundation::impl::SDKFoundation& wikitude::sdk_foundation::impl::ServiceManager::getHostSDKwikitude::sdk_foundation::impl::SDKFoundation() const", referenced from:
      wikitude::sdk_core::impl::CalibrationManager::finishCalibration() in libWikitudeSDK_simulator.a(CalibrationManager.o)
      wikitude::sdk_core::impl::CalibrationManager::targetRecognized(wikitude::sdk_foundation::impl::BaseTracker&, wikitude::sdk_foundation::impl::RecognizedTarget&) in libWikitudeSDK_simulator.a(CalibrationManager.o)
  "wikitude::sdk_core::impl::ArchitectEngine& wikitude::sdk_foundation::impl::ServiceManager::getHostSDKwikitude::sdk_core::impl::ArchitectEngine() const", referenced from:
      wikitude::sdk_core::impl::CalibrationManager::finishCalibration() in libWikitudeSDK_simulator.a(CalibrationManager.o)
      wikitude::sdk_core::impl::CalibrationManager::targetRecognized(wikitude::sdk_foundation::impl::BaseTracker&, wikitude::sdk_foundation::impl::RecognizedTarget&) in libWikitudeSDK_simulator.a(CalibrationManager.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

The following build commands failed:

```
Ld build/emulator/SunnyDiscover.app/SunnyDiscover normal i386
```

(1 failure)

Error code 65 for command: xcodebuild with args: -xcconfig,/Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/cordova/build-debug.xcconfig,-project,SunnyDiscover.xcodeproj,ARCHS=i386,-target,SunnyDiscover,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/build/sharedpch

ERROR building one of the platforms: Error: /Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project

Error: /Users/repixels/Desktop/Sunny/Phonegap Project/SunnyDiscover/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

Yet, I was able to build an earlier version of the project using Phonegap and Wikitude Plugin v4.1.0  - com.wikitude.phonegap.WikitudePlugin 4.1.0 , But had to disable the Bitcode in xcode to run this version.

**Comment by repixels** [comment]
Any Progress regarding the above error !?

**Comment by engbmsdev** [comment]
+1

**Comment by mladenp** [comment]
I need to disable Bitcode whenever i build cordova apps or else it won't build.

**Comment by drrasic** [comment]
use this build command instead:
cordova build ios --device

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi, the Wikitude SDK now supports Bitcode ([Version 7.0.0](http://www.wikitude.com/external/doc/documentation/latest/ios/changelog.html#wikitude-sdk-700)). Please let us know if you still encounter Bitcode related issues, thx!
