### ISSUE TITLE
Build process failed with Xcode 7 / iOS 9

### ISSUE THREAD

**Issue by mrbubbaz** [Wikitude/wikitude-cordova-plugin#90]
Build failed while I try to run standard build command:

[INF] [shellscript] Undefined symbols for architecture i386:
[INF] [shellscript]   "wikitude::sdk_foundation::impl::SDKFoundation& wikitude::sdk_foundation::impl::ServiceManager::getHostSDKwikitude::sdk_foundation::impl::SDKFoundation() const", referenced from:
[INF] [shellscript]       wikitude::sdk_core::impl::CalibrationManager::finishCalibration() in libWikitudeSDK_simulator.a(CalibrationManager.o)
[INF] [shellscript]       wikitude::sdk_core::impl::CalibrationManager::targetRecognized(wikitude::sdk_foundation::impl::BaseTracker&, wikitude::sdk_foundation::impl::RecognizedTarget&) in libWikitudeSDK_simulator.a(CalibrationManager.o)
[INF] [shellscript]   "wikitude::sdk_core::impl::ArchitectEngine& wikitude::sdk_foundation::impl::ServiceManager::getHostSDKwikitude::sdk_core::impl::ArchitectEngine() const", referenced from:
[INF] [shellscript]       wikitude::sdk_core::impl::CalibrationManager::finishCalibration() in libWikitudeSDK_simulator.a(CalibrationManager.o)
[INF] [shellscript]       wikitude::sdk_core::impl::CalibrationManager::targetRecognized(wikitude::sdk_foundation::impl::BaseTracker&, wikitude::sdk_foundation::impl::RecognizedTarget&) in libWikitudeSDK_simulator.a(CalibrationManager.o)
[INF] [shellscript] ld: symbol(s) not found for architecture i386
[INF] [shellscript] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[INF] [shellscript] 
[INF] [shellscript] ERROR building one of the platforms: Error: /Volumes/Documents/Users/simone/Documents/APPS/VDST/cordova/platforms/ios/cordova/build: Command failed with exit code 2

I think that the issue is related to simulator platform because it's possible to build for arm architecture and test on real device.

**Comment by AndreasSchacherbauerWikitude** [comment]
Yes, please build and test your application on a real device. The Wikitude SDK is usually able to build for the simulator but we're having some issues with the simulator right now.
Note that to actually use the Wikitude SDK, you would need to use a real device anyhow because the Simulator has no camera or sensor access.
