### ISSUE TITLE
The app references non-public symbols in ******: _dsyrk_

### ISSUE THREAD

**Issue by mrbubbaz** [Wikitude/wikitude-cordova-plugin#93]
Hello, I was trying to submit my app to iTunes connect but the binary was refused because of usage of non public symbols.
I suspect that problem is related to this plugin as mentioned in the wikitude forum:
http://www.wikitude.com/developer/developer-forum/-/message_boards/message/753976 wich suggest to download a newer version of the SDK. 
Cordova plugin however uses "libWikitudeSDK.a" instead of "WikitudeSDK.framework" which is in the package mentioned in the forum.

Any help to fix will be very appreciated....

**Comment by pnagele** [comment]
Have you tried the very recent pre-release in this branch https://github.com/Wikitude/wikitude-cordova-plugin/tree/release/v5.0.1-3.2.0?

**Comment by brunosouza** [comment]
Hi @pnagele i was unable to solve this issue. Can you help me?

**Comment by mrbubbaz** [comment]
Using the pre-release branch worked for me...

try run:
```
cordova plugin rm com.wikitude.phonegap.WikitudePlugin
```
wich remove the installed plugin, and then:
```
cordova plugin add  https://github.com/Wikitude/wikitude-cordova-plugin.git#v5.0.1-3.2.0-beta.1

```
to checkout the plugin from the prerelease tag

**Comment by brunosouza** [comment]
Hi Simone, thanks for the help, problem solved :D

Bruno Souza
81-9926.9883

**Comment by brunosouza** [comment]
Hi @mrbubbaz thanks for u help, problem solved :D
